project:
  type: book

execute: 
  warning: false
  echo: false

book:
  title: "Data Analysis for the Social Sciences"
  author: "Zacharia Bady"
  date: "10/14/2024"
  chapters:
    - index.qmd
    - intro.qmd
    #- Logic.qmd
    #- Probability.qmd
    #- summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    code-fold: true
    theme: 
      - Flatly
      - Flatly.scss
  #pdf:
  #  documentclass: scrbook
   # include-in-header:
  #    - file: "style.tex"

editor: visual

csl: apa.csl

